export const rituals = [
  { en: "Mehendi", bn: "মেহেন্দি" },
  { en: "Ashirbad", bn: "আশীর্বাদ" },
  { en: "Morning Special Moments", bn: "সকালের বিশেষ মুহূর্ত" },
  { en: "Briddhi", bn: "বৃদ্ধি" },
  { en: "Jol Sowa", bn: "জল সওয়া" },
  { en: "Gaye Holud", bn: "গায়ে হলুদ" },
  { en: "Venue Video", bn: "ভেন্যু ভিডিও" },
  { en: "Borjatri", bn: "বরযাত্রী" },
  { en: "Bor Boron", bn: "বর বরণ" },
  { en: "Bride Special Moments", bn: "কনের বিশেষ মুহূর্ত" },
  { en: "Family Group Moments", bn: "পরিবারের গ্রুপ মুহূর্ত" },
  { en: "Bostro Daan", bn: "বস্ত্র দান" },
  { en: "Saat Paak", bn: "সাত পাক" },
  { en: "Pan Pata Sorano", bn: "পান পাতা সরানো" },
  { en: "Hosto Bondhon", bn: "হস্ত বন্ধন" },
  { en: "Sindur Daan", bn: "সিঁদুর দান" },
  { en: "Couple Special Moments", bn: "দম্পতির বিশেষ মুহূর্ত" },
  { en: "Bidai", bn: "বিদায়" },
  { en: "Bodhu Boron", bn: "বধূ বরণ" },
  { en: "Bhat Kapor", bn: "ভাত কাপড়" },
  { en: "Venue Entry", bn: "ভেন্যু এন্ট্রি" },
  { en: "Group Video", bn: "গ্রুপ ভিডিও" },
  { en: "Food Section", bn: "খাবারের অংশ" },
  { en: "Dance", bn: "নাচ" },
  { en: "Audience Moments", bn: "অতিথিদের মুহূর্ত" },
  { en: "Bashor Ghor", bn: "বাসর ঘর" }
];
